SELECT ATTACH_OBJ_EVW.OBJECTID AS "Attach OBJ ObjectID", 
ATTACH_OBJ_EVW.OWNED_BY AS "Attachment Owner", 
ATTACH_OBJ_EVW.TYPE AS "Attachment Type", 
POLE_EVW.OBJECTID AS "Pole ObjectID", 
POLE_EVW.OWNED_BY AS "Pole Owner", 
POLE_EVW.POLE_USE, 
POLE_EVW.ORG_ID, 
ATTACH_OBJ_EVW.QUANTITY, 
POLE_EVW.COUNTY
FROM ATTACH_OBJ_EVW LEFT JOIN POLE_EVW ON ATTACH_OBJ_EVW.POLE_GUID = POLE_EVW.GLOBALID
ORDER BY ATTACH_OBJ_EVW.OBJECTID;
