SELECT DISGISDB.ATTACH_OBJ_EVW.OBJECTID AS "Attach OBJ ObjectID", 
DISGISDB.ATTACH_OBJ_EVW.OWNED_BY AS "Attachment Owner", 
DISGISDB.ATTACH_OBJ_EVW.TYPE AS "Attachment Type", 
DISGISDB.POLE_EVW.OBJECTID AS "Pole ObjectID", 
DISGISDB.POLE_EVW.OWNED_BY AS "Pole Owner", 
DISGISDB.POLE_EVW.POLE_USE, 
DISGISDB.POLE_EVW.ORG_ID, 
DISGISDB.ATTACH_OBJ_EVW.QUANTITY, 
DISGISDB.POLE_EVW.COUNTY
FROM DISGISDB.ATTACH_OBJ_EVW LEFT JOIN DISGISDB.POLE_EVW ON DISGISDB.ATTACH_OBJ_EVW.POLE_GUID = DISGISDB.POLE_EVW.GLOBALID
ORDER BY DISGISDB.ATTACH_OBJ_EVW.OBJECTID;