SELECT
    CASE 
        WHEN POLE_EVW.ORG_ID = 'ascst' THEN 'Coast'
        WHEN POLE_EVW.ORG_ID = 'ashttb' THEN 'PineBelt'
        WHEN POLE_EVW.ORG_ID = 'asmrd' THEN 'Meridian'
        ELSE 'Other'
    END AS Division, 
ATTACH_OBJ_EVW.TYPE, 
ATTACH_OBJ_EVW.OWNED_BY AS "Attachment Owner", 
Count(ATTACH_OBJ_EVW.OBJECTID) AS "Count", 
POLE_EVW.OWNED_BY, 
POLE_EVW.POLE_USE
FROM ATTACH_OBJ_EVW 
INNER JOIN POLE_EVW ON ATTACH_OBJ_EVW.POLE_GUID = POLE_EVW.GLOBALID
GROUP BY POLE_EVW.ORG_ID, ATTACH_OBJ_EVW.TYPE, ATTACH_OBJ_EVW.OWNED_BY, POLE_EVW.OWNED_BY, POLE_EVW.POLE_USE
HAVING (((ATTACH_OBJ_EVW.TYPE) != 'CTV') AND ((ATTACH_OBJ_EVW.OWNED_BY) != 'ATT' And (ATTACH_OBJ_EVW.OWNED_BY) Is Not Null) AND ((POLE_EVW.OWNED_BY)='MPC') AND ((POLE_EVW.POLE_USE)='DIST'))
ORDER BY POLE_EVW.ORG_ID;
