SELECT 
    CASE 
        WHEN DISGISDB.POLE_EVW.ORG_ID = 'ascst' THEN 'Coast'
        WHEN DISGISDB.POLE_EVW.ORG_ID = 'ashttb' THEN 'PineBelt'
        WHEN DISGISDB.POLE_EVW.ORG_ID = 'asmrd' THEN 'Meridian'
        ELSE 'Other'
    END AS Division, 
DISGISDB.POLE_EVW.OBJECTID, 
Count(DISGISDB.ATTACH_OBJ_EVW.TYPE) AS "Count per Pole"
FROM DISGISDB.ATTACH_OBJ_EVW 
INNER JOIN DISGISDB.POLE_EVW ON DISGISDB.ATTACH_OBJ_EVW.POLE_GUID = DISGISDB.POLE_EVW.GLOBALID
WHERE (((DISGISDB.POLE_EVW.POLE_USE)='DIST') AND ((DISGISDB.POLE_EVW.OWNED_BY)='MPC'))
GROUP BY DISGISDB.POLE_EVW.ORG_ID, DISGISDB.POLE_EVW.OBJECTID
HAVING (((Count(DISGISDB.ATTACH_OBJ_EVW.TYPE))>=2));