SELECT 
    CASE 
        WHEN SUBSTATION_EVW.ORG_ID = 'ascst' THEN 'Coast'
        WHEN SUBSTATION_EVW.ORG_ID = 'ashttb' THEN 'PineBelt'
        WHEN SUBSTATION_EVW.ORG_ID = 'asmrd' THEN 'Meridian'
        ELSE 'Other'
    END AS Division,
    SUBSTATION_EVW.SUBSTATION_NAME,
    GETAWAY_EVW.FEEDERID
FROM 
    GETAWAY_EVW 
    INNER JOIN SUBUNIT_EVW ON GETAWAY_EVW.SUBUNIT_GLOBALID = SUBUNIT_EVW.GLOBALID
    INNER JOIN SUBSTATION_EVW ON SUBUNIT_EVW.SUBSTATION_GLOBALID = SUBSTATION_EVW.GLOBALID
WHERE 
    GETAWAY_EVW.LAST_WE = 'N'
ORDER BY 
    CASE 
        WHEN SUBSTATION_EVW.ORG_ID = 'ascst' THEN 'Coast'
        WHEN SUBSTATION_EVW.ORG_ID = 'ashttb' THEN 'PineBelt'
        WHEN SUBSTATION_EVW.ORG_ID = 'asmrd' THEN 'Meridian'
        ELSE 'Other'
    END,
    SUBSTATION_EVW.SUBSTATION_NAME,
    GETAWAY_EVW.FEEDERID,
    GETAWAY_EVW.LAST_WE;
