SELECT 
    CASE 
        WHEN DISGISDB.SUBSTATION_EVW.ORG_ID = 'ascst' THEN 'Coast'
        WHEN DISGISDB.SUBSTATION_EVW.ORG_ID = 'ashttb' THEN 'PineBelt'
        WHEN DISGISDB.SUBSTATION_EVW.ORG_ID = 'asmrd' THEN 'Meridian'
        ELSE 'Other'
    END AS Division,
    DISGISDB.SUBSTATION_EVW.SUBSTATION_NAME,
    DISGISDB.GETAWAY_EVW.FEEDERID
FROM 
    DISGISDB.GETAWAY_EVW 
    INNER JOIN DISGISDB.SUBUNIT_EVW ON DISGISDB.GETAWAY_EVW.SUBUNIT_GLOBALID = DISGISDB.SUBUNIT_EVW.GLOBALID
    INNER JOIN DISGISDB.SUBSTATION_EVW ON DISGISDB.SUBUNIT_EVW.SUBSTATION_GLOBALID = DISGISDB.SUBSTATION_EVW.GLOBALID
WHERE 
    DISGISDB.GETAWAY_EVW.LAST_WE = 'N'
ORDER BY 
    CASE 
        WHEN DISGISDB.SUBSTATION_EVW.ORG_ID = 'ascst' THEN 'Coast'
        WHEN DISGISDB.SUBSTATION_EVW.ORG_ID = 'ashttb' THEN 'PineBelt'
        WHEN DISGISDB.SUBSTATION_EVW.ORG_ID = 'asmrd' THEN 'Meridian'
        ELSE 'Other'
    END,
    DISGISDB.SUBSTATION_EVW.SUBSTATION_NAME,
    DISGISDB.GETAWAY_EVW.FEEDERID,
    DISGISDB.GETAWAY_EVW.LAST_WE;