    SELECT DISGISDB.GENERATOR_EVW.FEEDERID, Sum(DISGISDB.GENERATOR_EVW.ACTIVE_GEN_KW) AS "KW Total"
    FROM DISGISDB.GENERATOR_EVW
    WHERE (((DISGISDB.GENERATOR_EVW.FACILITY_STATUS)='E') AND ((DISGISDB.GENERATOR_EVW.GEN_TYPE)='S') AND ((DISGISDB.GENERATOR_EVW.SUBTYPECD)=112))
    GROUP BY DISGISDB.GENERATOR_EVW.FEEDERID
    HAVING (((DISGISDB.GENERATOR_EVW.FEEDERID) != 'KC'))
    ORDER BY DISGISDB.GENERATOR_EVW.FEEDERID
