SELECT 
  CASE 
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 51 THEN '4 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 54 THEN '4 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 60 THEN '12 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 75 THEN '12 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 66 THEN '13.8 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 81 THEN '13.8 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 78 THEN '23 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 89 THEN '23 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 84 THEN '14.4 KV'
    ELSE 'Other'
  END AS Voltage,
  SUM(PRIMARY_OH_EVW.LENGTH / 5280) AS "OH Miles"
FROM 
  PRIMARY_OH_EVW
WHERE 
  PRIMARY_OH_EVW.OWNED_BY = 'MPC'
GROUP BY 
  CASE 
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 51 THEN '4 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 54 THEN '4 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 60 THEN '12 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 75 THEN '12 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 66 THEN '13.8 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 81 THEN '13.8 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 78 THEN '23 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 89 THEN '23 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 84 THEN '14.4 KV'
    ELSE 'Other'
  END
ORDER BY 
  CASE 
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 51 THEN '4 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 54 THEN '4 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 60 THEN '12 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 75 THEN '12 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 66 THEN '13.8 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 81 THEN '13.8 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 78 THEN '23 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 89 THEN '23 KV'
    WHEN PRIMARY_OH_EVW.OVOLTAGE = 84 THEN '14.4 KV'
    ELSE 'Other'
  END;
